### ISSUE TITLE
Something wrong, feel free to contact to resolve the issue. Take attendance manually for now.

### ISSUE THREAD

**Issue by cassio-tav** [KingMohan45/googleMeetAttendanceAndNotifier#1]
### Setup

- HP desktop with Intel Core i5 vPro
- NixOS 20.09.4055.eb7e1ef185f (Nightingale)
- Firefox for Wayland (xdg shell) 88.0 64bit
- Google Meet Attendance & Notifier 4.2.2 May 24, 2021

### Behavior

When I start a meeting (Google Meet) a dialog pops up with the message *“Something wrong, feel free to contact to resolve the issue. Take attendance manually for now.”* When I manually start recording, the same dialog pops up again, as it does subsequently on any action I take, or even if I don't do anything. Even after I stop recording the dialog keeps on coming.

**Comment by KingMohan45** [comment]
Hello @cassio-tav. Just now I checked the source code and verified with the Google meet web-page source. That may be the case that the people DIV isn't visible yet it can happen with poor internet connection.
Try the following solutions:
1. Make sure you have good internet connection
2. Sometimes some issues can be solved by pressing **Esc** key.
I hope there two approaches will solve the issue.
And happy see that you reported the issue without ignoring.
